---
name: CI check SonarQube

on:
  pull_request:
  workflow_dispatch:

jobs:
  Sonar-Analysis:
    name: Sonar analysis
    runs-on: 'prod-ubuntu-jammy'
    timeout-minutes: 30
    # Required to get secrets from AWS
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Sonar analysis
        id: sonar_analysis
        # temporary tag for the action, to be released!
        uses: DataDome/gha-commons/actions/common/sonar-analysis-action@v4.6.5
        with:
          application: ${{ github.event.repository.name }}
          qualityGate: false